import { Suspense } from 'react'
import './styles/globals.scss'
import { Inter } from 'next/font/google'
import Header from './header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Cory Ginsberg',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback="...">
          <Header />
        </Suspense>
        {children}
      </body>
    </html>
  )
}
